# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('mac_address', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('added', models.DateTimeField()),
                ('expires', models.DateTimeField()),
                ('added_by', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('personal', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceGroupAdmins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PennUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pennkey', models.CharField(max_length=255)),
                ('lastLogin', models.DateTimeField(auto_now=True)),
                ('siteAdmin', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='devicegroupadmins',
            name='admins',
            field=models.ManyToManyField(to='registration.PennUser'),
        ),
        migrations.AddField(
            model_name='devicegroupadmins',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.DeviceGroup'),
        ),
        migrations.AddField(
            model_name='devicegroup',
            name='members',
            field=models.ManyToManyField(to='registration.PennUser'),
        ),
        migrations.AddField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.DeviceGroup'),
        ),
    ]
