# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_device_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pennuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='pennuser',
            name='pennkey',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
