# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20161202_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicegroup',
            name='specialRole',
            field=models.BooleanField(default=True),
        ),
    ]
