# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 21:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_devicegroup_specialrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicegroup',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='devicegroupadmins',
            name='admins',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
