# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20161207_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicegroup',
            name='specialRole',
            field=models.BooleanField(default=False),
        ),
    ]
