# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 15:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0011_auto_20161219_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicegroup',
            name='admins',
            field=models.ManyToManyField(related_name='admins', to=settings.AUTH_USER_MODEL),
        ),
    ]
