# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_auto_20161220_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='added_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='expires',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.DeviceGroup'),
        ),
    ]
