# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 04:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_auto_20161220_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicegroup',
            name='admins',
            field=models.ManyToManyField(null=True, related_name='group_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
