# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 20:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_merge_20161221_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.CharField(max_length=17, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Please enter a valid MAC Address', regex='([0-9a-fA-F]{2}:){5}[0-9a-fA-F]{2}')]),
        ),
    ]
